# Generated by Django 5.1.1 on 2024-10-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='firstname',
            field=models.CharField(default='omar', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.CharField(default='omar', max_length=100),
        ),
    ]
