# Generated by Django 5.1.1 on 2024-10-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_users_firstname_alter_users_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='hi', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
