# Generated by Django 5.1.1 on 2024-10-04 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_users_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
