# Generated by Django 5.1.1 on 2024-10-04 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_firstname_users_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='userName',
        ),
    ]
